-- MySQL Script generated by MySQL Workbench
-- Wed May 19 13:36:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema annoncesfaciles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema annoncesfaciles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `annoncesfaciles` DEFAULT CHARACTER SET utf8 ;
USE `annoncesfaciles` ;

-- -----------------------------------------------------
-- Table `annoncesfaciles`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annoncesfaciles`.`Users` ;

CREATE TABLE IF NOT EXISTS `annoncesfaciles`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(25) NOT NULL,
  `mail` VARCHAR(60) NOT NULL,
  `type` TINYINT(2) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `UniqueUser` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `annoncesfaciles`.`Advertisements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annoncesfaciles`.`Advertisements` ;

CREATE TABLE IF NOT EXISTS `annoncesfaciles`.`Advertisements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(40) NOT NULL,
  `category` TINYINT(3) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  `image` VARCHAR(128) NULL,
  `price` DECIMAL(2) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `UniqueAdvertisement` (`title` ASC, `description` ASC, `image` ASC, `price` ASC) VISIBLE,
  INDEX `fk_Advertisements_Users_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Advertisements_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `annoncesfaciles`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
